name: Test Flast API

on:
  push:
    branches: main
  pull_request:
    branches: main

#Task
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # To clone code to work on
      - name: Test VM 
      # Terminal
        run: ls 